apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-testapp
  labels:
    app: testapp
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: testapp
