apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ .Values.vaultPullSecret.name }}
spec:
  keys:
    - .dockerconfigjson
  path: {{ .Values.vaultPullSecret.path }}
  type: kubernetes.io/dockerconfigjson