default:
  tag: &tag master
  repoURL: &repoURL https://github.com/nattvasan/testapp.git
  helmValuesFile: &helmValuesFile values.yaml
  targetRevision: &targetRevision main


applications:
  redis:
    namespace: testapp
    argocdProject: webapp
    source:
      path: helm/webapp
      repoURL: *repoURL
      targetRevision: *targetRevision
      valuesFile: *helmValuesFile